### ISSUE TITLE
'lost an election struct between looking it up and reading it'

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2177]
Well who would have thought but I just observed [this .expect()](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/src/server/mod.rs#L517-L518) failing.

Context:
I'm testing the resilience of an HA PostgreSQL plan by starting 3 nodes writing to the leader and then stopping / starting individual nodes to make sure that the value has been correctly replicated and that a new leader will properly come up once quorum has been restored.

I am just developing the test, and this is the first time I have observed this so I don't know if it is reproducible.
Steps taken were:
- start 3 nodes
- write value
- stop 2 nodes
- read value
- start 2 nodes
- wait for leader to emerge (FAIL)

output of the containers when they were started up again:
pg1
```
hab-sup(MN):
hab-sup(MN): WARNING: Setting '--config-from /conf' should only be used in development, not production!
hab-sup(MN):
hab-sup(MR): Butterfly Member ID 2525fb985cd54cf194a21da476616edc
hab-sup(SR): Adding starkandwayne/postgresql/9.6.1/20170426170728
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
connecting to tcp://localhost:10001
connecting to tcp://localhost:10011
connecting to tcp://localhost:10021
postgresql.cluster(SR): Executing hooks; fc887bb1ce324fdd99598ac2fdbfc1a4 is the leader
postgresql.cluster(SR): Initializing
postgresql.cluster hook[init]:(HK): Bootstrapping from leader
Could not send rumor to Member { proto: id: "222ff080a09a4dee87d20daf93597107" incarnation: 0 address: "172.30.0.3" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "222ff080a09a4dee87d20daf93597107" incarnation: 0 address: "172.30.0.3" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
postgresql.cluster(SV): Starting process as user=hab, group=hab
thread 'main' panicked at 'Lost an election struct between looking it up and reading it.', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
note: Run with `RUST_BACKTRACE=1` for a backtrace.
postgresql.cluster hook[suitability]:(HK): psql: could not connect to server: Connection refused
```

pg2
```
hab-sup(MN):
hab-sup(MN): WARNING: Setting '--config-from /conf' should only be used in development, not production!
hab-sup(MN):
hab-sup(MR): Butterfly Member ID 222ff080a09a4dee87d20daf93597107
hab-sup(SR): Adding starkandwayne/postgresql/9.6.1/20170426170728
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
connecting to tcp://localhost:10001
connecting to tcp://localhost:10011
connecting to tcp://localhost:10021
postgresql.cluster(SR): Executing hooks; fc887bb1ce324fdd99598ac2fdbfc1a4 is the leader
postgresql.cluster(SR): Initializing
postgresql.cluster hook[init]:(HK): Bootstrapping from leader
Could not write our own rumor to bytes; abandoning sending rumor: NonExistentRumor("election", "postgresql.cluster")
postgresql.cluster(SV): Starting process as user=hab, group=hab
thread 'main' panicked at 'Lost an election struct between looking it up and reading it.', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
note: Run with `RUST_BACKTRACE=1` for a backtrace.
postgresql.cluster(O): Starting PostgreSQL
```

pg3
```
hab-sup(MN):
hab-sup(MN): WARNING: Setting '--config-from /conf' should only be used in development, not production!
hab-sup(MN):
hab-sup(MR): Butterfly Member ID fc887bb1ce324fdd99598ac2fdbfc1a4
hab-sup(SR): Adding starkandwayne/postgresql/9.6.1/20170426170728
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
ERROR:habitat_butterfly::server::outbound: Discarding ack from b4254c207d854ec8b8402abc5cb20d93@172.30.0.2:9638; expected 222ff080a09a4dee87d20daf93597107
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
connecting to tcp://localhost:10001
connecting to tcp://localhost:10011
connecting to tcp://localhost:10021
hab-sup(SC): Updated pg_hba.conf 0bf942c14bab24fc19481fbf74740fcea7aff4be99e7571feb5227d45465a95a
hab-sup(SC): Updated postgresql.conf 362d8069c82998404586643a15bb3af5494f47e0f77139b106895f63f0197d4c
hab-sup(SC): Updated pwfile 30087c89f3dfc2b2179a2b567a67f094cf1cd8b1c6e3cc1473aef95fe65de533
hab-sup(SC): Updated recovery.conf 97db4769e48eb70e727fe1652cbdabad8b2eceace3f023268bcb9c2e664a6617
postgresql.cluster(SR): Waiting to execute hooks; election in progress, and we have no quorum.
hab-sup(SC): Updated recovery.conf 27038fd817ddcdb4d30e5f3698542036199ce3311e591abcf484fdae0a2956db
postgresql.cluster(SR): Executing hooks; fc887bb1ce324fdd99598ac2fdbfc1a4 is the leader
postgresql.cluster(SR): Initializing
postgresql.cluster hook[init]:(HK):  Database does not exist, creating with 'initdb'
postgresql.cluster hook[init]:(HK): The files belonging to this database system will be owned by user "hab".
postgresql.cluster hook[init]:(HK): This user must also own the server process.
postgresql.cluster hook[init]:(HK):
postgresql.cluster hook[init]:(HK): The database cluster will be initialized with locale "en_US.UTF-8".
postgresql.cluster hook[init]:(HK): The default text search configuration will be set to "english".
postgresql.cluster hook[init]:(HK):
postgresql.cluster hook[init]:(HK): Data page checksums are disabled.
postgresql.cluster hook[init]:(HK):
postgresql.cluster hook[init]:(HK): fixing permissions on existing directory /hab/svc/postgresql/data ... ok
postgresql.cluster hook[init]:(HK): creating subdirectories ... ok
postgresql.cluster hook[init]:(HK): selecting default max_connections ... 100
postgresql.cluster hook[init]:(HK): selecting default shared_buffers ... 128MB
postgresql.cluster hook[init]:(HK): selecting dynamic shared memory implementation ... posix
postgresql.cluster hook[init]:(HK): creating configuration files ... ok
postgresql.cluster hook[init]:(HK): running bootstrap script ... ok
postgresql.cluster hook[init]:(HK): performing post-bootstrap initialization ... ok
postgresql.cluster hook[init]:(HK): syncing data to disk ... ok
postgresql.cluster hook[init]:(HK):
postgresql.cluster hook[init]:(HK): WARNING: enabling "trust" authentication for local connections
postgresql.cluster hook[init]:(HK): You can change this by editing pg_hba.conf or using the option -A, or
postgresql.cluster hook[init]:(HK): --auth-local and --auth-host, the next time you run initdb.
postgresql.cluster hook[init]:(HK):
postgresql.cluster hook[init]:(HK): Success. You can now start the database server using:
postgresql.cluster hook[init]:(HK):
postgresql.cluster hook[init]:(HK):     pg_ctl -D /hab/svc/postgresql/data -l logfile start
postgresql.cluster hook[init]:(HK):
postgresql.cluster(SV): Starting process as user=hab, group=hab
postgresql.cluster(O): Starting PostgreSQL
postgresql.cluster(O): 2017-04-27 09:00:42.471 GMT: LOG:  redirecting log output to logging collector process
postgresql.cluster(O): 2017-04-27 09:00:42.471 GMT: HINT:  Future log output will appear in directory "/hab/svc/postgresql/var/pg_log".
Could not send rumor to Member { proto: id: "222ff080a09a4dee87d20daf93597107" incarnation: 0 address: "172.30.0.3" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 0 address: "172.30.0.6" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
postgresql.cluster hook[suitability]:(HK): 100663392
postgresql.cluster(HK): Reporting suitability of: 100663392
hab-sup(SC): Updated recovery.conf 97db4769e48eb70e727fe1652cbdabad8b2eceace3f023268bcb9c2e664a6617
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 0 address: "172.30.0.6" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
postgresql.cluster(SR): Waiting to execute hooks; election in progress, and we have no quorum.
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "222ff080a09a4dee87d20daf93597107" incarnation: 2 address: "172.30.0.3" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
Could not send rumor to Member { proto: id: "2525fb985cd54cf194a21da476616edc" incarnation: 1 address: "172.30.0.4" swim_port: 9638 gossip_port: 9638 persistent: false }; ZMQ said: Resource temporarily unavailable
hab-sup(MR): Shutting down starkandwayne/postgresql/9.6.1/20170426170728
postgresql.cluster(SV): Stopping...
hab-sup(SV): postgresql.cluster - Shutdown method: Graceful Termination
hab-sup(SV): postgresql.cluster - process 61 died with exit code 0
hab-sup(MR): Habitat thanks you - shutting down!
```

Don't really know what to conclude from this other than we probably have too many `.expect()` calls in the code.
Will see if its reproducible.

**Comment by bodymindarts** [comment]
[this](https://github.com/starkandwayne/habitat-plans/blob/master/postgresql/tests/delmo.yml#L15-L37) is the current version of the test.
It doesn't fail consistently but I have observed corruption (like the one above) multiple times.

**Comment by adamhjk** [comment]
I suspect this has something to do with bringing the supervisors back on-line, and the way the election rumors get re-hydrated. This is pure suspicion at this point.

**Comment by christophermaier** [comment]
@bodymindarts I'm going to start digging into this today. As a preliminary to that, do you still see this behavior with the 0.28.0 (i.e., current latest) supervisor?

Thanks!

**Comment by christophermaier** [comment]
Updating for context: [this](https://github.com/habitat-sh/habitat/blob/53b5af90ddaba65096a7b3f959a04196e66a93f1/components/butterfly/src/server/mod.rs#L517-L518) is the `expect` call that was failing.

(The original link was to the file on `master`, which has moved on since this issue was posted, and not a specific commit.)

**Comment by bodymindarts** [comment]
@christophermaier after setting up this scenario with hab v0.28.0 I have not been able to reproduce this behaviour.

**Comment by bodymindarts** [comment]
I'll close it for now and reopen if I do see it again.

**Comment by adamhjk** [comment]
Amazing!

**Comment by christophermaier** [comment]
@bodymindarts Nice, thanks!
