### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by LiliC** [habitat-sh/habitat#3105]
We have noticed random failures while testing with the Node.js example application running on Kubernetes with the [Habitat Operator](https://github.com/kinvolk/habitat-operator). They seem to just produce an endless loop of retries with no real error to show. As per suggestion from @christophermaier on Slack I am opening this issue. 

The errors are very random occurring. For example:
```
...
mytutorialapp.nodejs(CF): Updated config.json 72fc329f86ff272f5f94ff26d313f962b94a0216a31161a6439d02c0ecda9da9
mytutorialapp.nodejs(SR): Configuration recompiled
mytutorialapp.nodejs(SR): Initializing
mytutorialapp.nodejs(SV): Starting service as user=hab, group=hab
mytutorialapp.nodejs(O): /hab/pkgs/lili/mytutorialapp/0.2.0/20170802095853/node_modules/nconf/lib/nconf/stores/file.js:33
mytutorialapp.nodejs(O):   this.dir     = options.dir    || process.cwd();
mytutorialapp.nodejs(O):                                            ^
mytutorialapp.nodejs(O):
mytutorialapp.nodejs(O): Error: ENOENT: no such file or directory, uv_cwd
mytutorialapp.nodejs(O):     at Error (native)
mytutorialapp.nodejs(O):     at new exports.File (/hab/pkgs/lili/mytutorialapp/0.2.0/20170802095853/node_modules/nconf/lib/nconf/stores/file.js:33:44)
mytutorialapp.nodejs(O):     at Provider.create (/hab/pkgs/lili/mytutorialapp/0.2.0/20170802095853/node_modules/nconf/lib/nconf/provider.js:163:10)
mytutorialapp.nodejs(O):     at Provider.add (/hab/pkgs/lili/mytutorialapp/0.2.0/20170802095853/node_modules/nconf/lib/nconf/provider.js:134:28)
mytutorialapp.nodejs(O):     at Provider.file (/hab/pkgs/lili/mytutorialapp/0.2.0/20170802095853/node_modules/nconf/lib/nconf/provider.js:63:15)
mytutorialapp.nodejs(O):     at Object.<anonymous> (/hab/pkgs/lili/mytutorialapp/0.2.0/20170802095853/server.js:5:7)
mytutorialapp.nodejs(O):     at Module._compile (module.js:570:32)
mytutorialapp.nodejs(O):     at Object.Module._extensions..js (module.js:579:10)
mytutorialapp.nodejs(O):     at Module.load (module.js:487:32)
mytutorialapp.nodejs(O):     at tryModuleLoad (module.js:446:12)
mytutorialapp.nodejs(SV): Starting service as user=hab, group=hab
mytutorialapp.nodejs(SR): Service restart failed: hab-sup(ER)[src/error.rs:474:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
mytutorialapp.nodejs(SV): Starting service as user=hab, group=hab
mytutorialapp.nodejs(SR): Service restart failed: hab-sup(ER)[src/error.rs:474:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
mytutorialapp.nodejs(SV): Starting service as user=hab, group=hab
mytutorialapp.nodejs(SR): Service restart failed: hab-sup(ER)[src/error.rs:474:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
mytutorialapp.nodejs(SV): Starting service as user=hab, group=hab
...
```
Another one:
```
∵ Missing package for core/hab-launcher
» Installing core/hab-launcher
↓ Downloading core/hab-launcher/4571/20170727193541
☛ Verifying core/hab-launcher/4571/20170727193541
→ Using core/bzip2/1.0.6/20170513212938
→ Using core/cacerts/2017.01.18/20170513215104
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
→ Using core/libarchive/3.2.0/20170514021649
→ Using core/libsodium/1.0.11/20170514010744
→ Using core/linux-headers/4.3/20170513200956
→ Using core/openssl/1.0.2j/20170513215106
→ Using core/xz/5.2.2/20170513214327
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/hab-launcher/4571/20170727193541
★ Install of core/hab-launcher/4571/20170727193541 complete with 1 new packages installed.
hab-sup(MR): Supervisor Member-ID 0b518989a1db4d2a959aeee53b26153d
hab-sup(MR): Starting lili/mytutorialapp
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
mytutorialapp.foobar(SR): Hooks recompiled
foobar(CF): Updated config.json 4e9defdc792c6c7256fa1f2be2730e7c6ee8d534d5da171b2204845772305999
mytutorialapp.foobar(SR): Configuration recompiled
mytutorialapp.foobar(SR): Initializing
mytutorialapp.foobar(SV): Starting service as user=hab, group=hab
mytutorialapp.foobar(SR): Service start failed: hab-sup(ER)[src/error.rs:474:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
mytutorialapp.foobar(SV): Starting service as user=hab, group=hab
...
```

The frequency of this affects the Habitat Operator end-to-end tests. The frequency is somewhere around 1 out of 10. To be able to more stabilise this and also to better the Kubernetes experience when using Habitat, maybe we could do two things:
- Make error msgs more useful (would be very useful to see what actually goes wrong, and if there is something we can do to fix it) (note: I have yet to try with the debug flag, will report back when I do.)
- Limit the number of Supervisor retries, for example with a flag. In the current scenario it keeps retrying, we could for Kubernetes world limit retries and eventually fail. This would be very useful as the pod would be restarted on failure and a new one would spawn up and successfully create a new service (that's what we are seeing right now, when we manually restart the pod).

**Comment by christophermaier** [comment]
@LiliC Thanks for filing the issue. Offhand I'm not sure exactly what's going on, but some related information for you:

1) that "Missing package for hab-launcher" line should go away with https://github.com/habitat-sh/habitat/pull/3100, which was merged yesterday. When you export a new container now, it should already have the launcher baked in.

2) Per your second suggestion, we have talked about limiting retries for this very use case. I think we will probably implement that, but I'm not sure of a timeline just yet.

**Comment by rsertelon** [comment]
@LiliC Has there been any improvements on this one? thanks :)

**Comment by LiliC** [comment]
@rsertelon not that I am aware, but haven't noticed it much lately come to think about it.

**Comment by rsertelon** [comment]
@LiliC I think @christophermaier might have found the problem for 2 in #3468 :)

**Comment by ozzyogkush** [comment]
I am seeing this behavior as well. When my node app throws an uncaught exception, it tries running the `run` hook over and over. If there's a way to limit retries that would be ideal.

**Comment by elliott-davis** [comment]
Closing in favor of: #4676
