### ISSUE TITLE
[STABILITY] [Supervisor] build worker crash in live - missing hab file uploaded file.

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4012]
Seeing some workers crashing in live:

```
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O): thread 'job_runner' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No su
ch file or directory" } }', /checkout/src/libcore/result.rs:906:4
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O): note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O): stack backtrace:
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    1: std::sys_common::backtrace::_print
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/sys_common/backtrace.rs:71
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    2: std::panicking::default_hook::{{closure}}
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/sys_common/backtrace.rs:60
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/panicking.rs:381
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    3: std::panicking::default_hook
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/panicking.rs:397
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    4: std::panicking::rust_panic_with_hook
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/panicking.rs:611
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    5: std::panicking::begin_panic
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/panicking.rs:572
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    6: std::panicking::begin_panic_fmt
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/panicking.rs:522
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    7: rust_begin_unwind
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libstd/panicking.rs:498
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    8: core::panicking::panic_fmt
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libcore/panicking.rs:71
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):    9: core::result::unwrap_failed
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libcore/macros.rs:41
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):   10: frank_jwt::read_pem
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./checkout/src/libcore/result.rs:772
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./root/.cargo/git/checkouts/frank_jwt-00dad275f4942a4e/48572b5/src/lib.rs:198
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):   11: frank_jwt::encode
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./root/.cargo/git/checkouts/frank_jwt-00dad275f4942a4e/48572b5/src/lib.rs:170
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./root/.cargo/git/checkouts/frank_jwt-00dad275f4942a4e/48572b5/src/lib.rs:112
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):   12: github_api_client::client::generate_app_token
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./src/components/github-api-client/src/client.rs:320
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):   13: github_api_client::client::GitHubClient::app_installation_token
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at ./src/components/github-api-client/src/client.rs:112
Nov 06 19:02:04 ip-10-0-0-76 hab[3461]: builder-worker.live(O):   14: habitat_builder_worker::vcs::VCS::clone
Nov 06 19:02:05 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at src/vcs.rs:73
Nov 06 19:02:05 ip-10-0-0-76 hab[3461]: builder-worker.live(O):   15: habitat_builder_worker::runner::Runner::run
Nov 06 19:02:05 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at src/runner/mod.rs:192
Nov 06 19:02:05 ip-10-0-0-76 hab[3461]: builder-worker.live(O):              at src/runner/mod.rs:310
Nov 06 19:09:20 ip-10-0-0-76 hab[3461]: builder-worker.live(HK): Hooks compiled
```

**Comment by chefsalim** [comment]
Looks like this panicked because the builder-github-app.pem file is missing in the svc/files directory.

**Comment by chefsalim** [comment]
So it looks like 'hab file upload' needs to get run every time nodes are re-provisioned - unlike the other configs, the files are not automatically updated on the nodes. Something we need to look at fixing potentially.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #70](https://github.com/habitat-sh/builder/issues/70) via [**ZenHub**](https://www.zenhub.com/)
