### ISSUE TITLE
binlink needs to generate wrappers

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#4493]
When a bin gets binlinked, `PATH` and any arbitrary runtime environment variables defined through `plan.sh`'s new mechanism for setting runtime environment variables are not set. This leads to a fundamental difference between using `hab pkg exec ...` and using a binlink, where `hab pkg exec` is the only way to consistently honor the runtime specifications of `plan.sh`

In what seems like an attempt to work around the `PATH` limitation, `hab pkg install -b` will binlink not just every script in the target package, but every script in every dependency too. This pollutes the bin and only partially addresses the need for binlinked scripts to have complete environments. One major problem with this approach is that binlinking packages that depend on different versions of the same package will lead to a single version of that dependency being used by both.

In order to provide a PATH for every bin script that matches the versions it was built against and provides for arbitrary runtime variables defined in `plan.sh`, some sort of wrapper script will be needed. Perhaps rather than writing symlinks, a wrapper script with PATH and other env variables being sourced or copied from `RUNTIME_ENVIRONMENT` could be generated.

Or, if it is preferable to keep using symlinks that semantically identify what they're pointing at, maybe the scripts could be written to `/hab/bin/command` or `/hab/bin/origin/pkg/version/build/command` and then the bin target symlinked to that

**Comment by themightychris** [comment]
This is related to #2376 but supersedes it in scope

**Comment by themightychris** [comment]
Use case: `csvkit`

Here's a plan for a python application that provides a bunch of command-line tools for manipulating CSVs: https://github.com/JarvusInnovations/habitat-plans/tree/master/csvkit

It is published to `jarvus/csvkit`

`hab pkg exec` works:
```
[1][default:/src:0]# hab pkg exec jarvus/csvkit csvsort --help
usage: csvsort [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
               [-p ESCAPECHAR] [-z FIELD_SIZE_LIMIT] [-e ENCODING] [-L LOCALE]
               [-S] [--blanks] [--date-format DATE_FORMAT]
               [--datetime-format DATETIME_FORMAT] [-H] [-K SKIP_LINES] [-v]
               [-l] [--zero] [-V] [-n] [-c COLUMNS] [-r] [-y SNIFF_LIMIT] [-I]
               [FILE]

Sort CSV files. Like the Unix "sort" command, but for tabular data.

...
```

binlink crashes:
```
[2][default:/src:0]# hab pkg binlink jarvus/csvkit csvsort
» Binlinking csvsort from jarvus/csvkit into /hab/bin
★ Binlinked csvsort from jarvus/csvkit/1.0.2/20180124155748 to /hab/bin/csvsort
```
```
[3][default:/src:0]# csvsort --help
Traceback (most recent call last):
  File "/hab/bin/csvsort", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'csvkit==1.0.2' distribution was not found and is required by the application
```

The missing ingredient:
```
[4][default:/src:1]# cat /hab/pkgs/jarvus/csvkit/1.0.2/20180124155748/RUNTIME_ENVIRONMENT
PATH=/hab/pkgs/jarvus/csvkit/1.0.2/20180124155748/bin:/hab/pkgs/core/python/3.6.3/20171014214215/bin:/hab/pkgs/core/sqlite/3130000/20170514005747/bin:/hab/pkgs/core/openssl/1.0.2l/20171014213633/bin:/hab/pkgs/core/ncurses/6.0/20170513213009/bin:/hab/pkgs/core/glibc/2.22/20170513201042/bin:/hab/pkgs/core/gdbm/1.11/20170513213716/bin:/hab/pkgs/core/bzip2/1.0.6/20170513212938/bin
PYTHONPATH=/hab/pkgs/jarvus/csvkit/1.0.2/20180124155748/lib/python3.6/site-packages:/hab/pkgs/core/python/3.6.3/20171014214215/lib/python3.6/site-packages
```

A workaround:
```
[5][default:/src:0]# export $(cat /hab/pkgs/jarvus/csvkit/1.0.2/20180124155748/RUNTIME_ENVIRONMENT | xargs) && csvsort --help
usage: csvsort [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
               [-p ESCAPECHAR] [-z FIELD_SIZE_LIMIT] [-e ENCODING] [-L LOCALE]
               [-S] [--blanks] [--date-format DATE_FORMAT]
               [--datetime-format DATETIME_FORMAT] [-H] [-K SKIP_LINES] [-v]
               [-l] [--zero] [-V] [-n] [-c COLUMNS] [-r] [-y SNIFF_LIMIT] [-I]
               [FILE]

Sort CSV files. Like the Unix "sort" command, but for tabular data.

...
```

**Comment by themightychris** [comment]
The wrapper scripts should probably append existing env vars, e.g. `export PATH="${PATH}:/hab/pkgs/..."`

**Comment by qubitrenegade** [comment]
#1780 I think would benefit from this as well.

Essentially, Python can't find the module that has been installed to `$(hab pkg path core/docutils)/lib` since it's not in the `PYTHONPATH`

Should I be able to execute `$(hab pkg path jarvus/csvkit)/bin/cvssort`?  Or should the user experience be "you have to `hab pkg exec jarvus/csvkit cvssort` or `--binlink` to use this executable"?  (I don't know the answer, but for debugging purposes I've definitely typed the fully qualified path to executables... maybe this is bad behavior?)

**Comment by themightychris** [comment]
@qubitrenegade my feeling is that for debugging purposes, do whatever helps you with poking things under /hab/pkg/* directly, bin or no bin. However, habitat isn't just delivering a pile of files to the machine, it's giving the you the means to define the environment it runs within. For that to work, there's no getting around needing to put code in between the user and underlying binaries the package builds.

If the /bin directory within the package was full of wrapped scripts, then the underlying binaries would just need to be somewhere else in there instead and someone could still run them directly if they wanted.

FWIW I think `hab pkg exec` and `--binlink` should be the two official ways to run provided commands with the habitat-managed runtime environment in place. Both should behave the same way, which means `--binlink` should generate short wrapper scripts rather than symlinks.

**Comment by qubitrenegade** [comment]
@themightychris I guess my point was more, other than for debugging purposes, _I_ can't think of another legitimate reason to be running `/hab/pkgs/foo/0.1.0/943143219234914/bin/foo`...  So perhaps as you point out, we should be espousing a "don't run things directly" mantra (e.g.: either use `hab pkg exec` or `--binlink` only).

To that end, what _should_ `hab pkg exec` do?  Because in #1780 `hab pkg exec core/docutils` was still failing because it wasn't setting the `PYTHONPATH` variable... (while it's entirely possible that I overlooked something in the plan to make that work) I had to create my wrapper manually.

So perhaps the best course of action is to have a flag "generate wrappers" in the plan, put the actual executables in `real_bin/` and the wrappers in `bin/`?  (but back to my initial point is there a use case for running the `/hab/pkg/*` directly?)

Again, I don't know what the right answer is here, I'm mostly thinking out loud.

**Comment by themightychris** [comment]
As a plan developer, if I use the `do_setup_environment` and `push_runtime_env` or even just `pkg_deps` I'm already declaring that my executables have runtime requirements in a direct and semantic way. IMO having a plan-level option for whether or not wrappers should be generated would be redundant and a leaky abstraction.

During the build process habitat is already generating files that provide the runtime environment, `--binlink` just needs to write a script that sources that env. If someone just wanted a symlink to a file inside the package they could make it themselves, asking habitat to do it for you is telling habitat you want the command available on your system and you want habitat to make it work with all its habitat goodness.

**Comment by themightychris** [comment]
@qubitrenegade regarding habitat-sh/core-plans#1780 it looks like `docutils` isn't yet making use of the new `push_runtime_env` feature which is the managed way to address that

**Comment by qubitrenegade** [comment]
@themightychris oh hmm... I hadn't heard about `push_runtime_env` yet.  I _think_ that actually answers my above question...?  (guys, mind halting development until I catch up with all the new features please? 😀)

I guess my question really boils down to:

"Should running `/hab/pkg/core/foo/0.1.0/423454325243/bin/foo` have the same user experience as running `hab pkg exec core/foo foo`/`hab pkg binlink core/foo; foo`"?

And I think the answer that we're arriving at is, no, it shouldn't be the same experience as `/hab/pkg////foo` is not the canonical way to run a Habitat package.  Which I think is a totally fair answer.

> IMO having a plan-level option for whether or not wrappers should be generated would be redundant and a leaky abstraction.

Ok, I'll buy that.  That makes sense to me.

**Comment by jamessewell** [comment]
@themightychris you mentioned above that 

> The wrapper scripts should probably append existing env vars, e.g. `export PATH="${PATH}:/hab/pkgs/..."`

But wouldn't the scripts just be a call to:

`hab pkg exec origin/package $ARGS`

That way you guarantee that  `wrapper == exec`

**Comment by jamessewell** [comment]
Just doing some testing now.

On Linux everything is peachy if I create this:

```
 #!/bin/sh
/hab/bin/hab pkg exec jirotech/cellfix cellfix_ng.py "$@"
```
and put it in  `/hab/binlink/jirotech/cellfix/1.0/2018091301383/cellfix_ng.py`

Then link that to /usr/bin/cellfix_ng

Can anyone see any issues with this approach?

**Comment by themightychris** [comment]
Oh, that approach hadn't even occurred to me... seems ideal as far as I can tell

**Comment by jamessewell** [comment]
Can I get some eyes on this? Don't want to PR yet as Windows support isn't in there - works on Linux well though.

https://github.com/jamessewell/habitat/tree/binlinkstubs

**Comment by themightychris** [comment]
@jamessewell looks awesome to me

Is opening PRs on things that still need work frowned upon? Now that the desired functionality is ironed out I feel like a PR stands a better chance of keeping what needs to get done to close the gap in focus. IMO we can wrap up discussing the issue and shift to discussing the implementation, this satisfies all the reasons I had to open this issue

**Comment by rsertelon** [comment]
Yeah opening a PR is the best way to make this move forward IMHO :)

**Comment by jamessewell** [comment]
There has been a PR for quite a while- https://github.com/habitat-sh/habitat/pull/5696

I've been waiting on some more comments before I invest some more time.

**Comment by themightychris** [comment]
was there ever any follow-up to #6812 and #6796 in anyones mind or are first-class linux binstubs pretty much dead?

**Comment by qubitrenegade** [comment]
Any thoughts?

I'd love to close the loop...
