### ISSUE TITLE
Failure to create projects / hitting github rate limit issue

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4549]
We are seeing reports of people unable to connect plan files to repos.
This is potentially due to hitting github rate limits with searches in orgs with lots of repos.

Example report below:
```
Is the GitHub "Set path to Habitat plan file" not currently working? I'm retrying the demo and it doesn't currently work for me
3 different browsers, uninstalled/reinstalled GitHub App
finds mattray/sample-node-app but not habitat/plans.sh
and it doesn't seem to work with current habitat https://gist.github.com/b7fb6149e39c1d40256d05036762264e

shared this Plain Text snippet: *shell*.txt 
$ docker run -it -p 8000:8000 mattray/sample-node-app
hab-sup(MR): Supervisor Member-ID 6921d086d07446ca9aeccd2aabececaa
hab-sup(MR): Starting mattray/sample-node-app
sample-node-app.default(UCW): Watching user.toml
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
sample-node-app.default(HK): init, compiled to /hab/svc/sample-node-app/hooks/init
sample-node-app.default(HK): Hooks compiled
sample-node-app.default(SR): Hooks recompiled
default(CF): Updated config.json 3f22842e8d737bbb107d9ac19afba42642eccf68a06ddfbdba70507b23b8498a
default(CF): Updated app_env.sh 9c88a9595def28f5914f08997b3cd3ba8d32f0e3eb2b4e4ea90264acd6acb66b
sample-node-app.default(SR): Configuration recompiled
sample-node-app.default(SR): Initializing
sample-node-app.default(SV): Starting service as user=hab, group=hab
sample-node-app.default(O): fs.js:646
sample-node-app.default(O):  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
sample-node-app.default(O):         ^
sample-node-app.default(O): 
sample-node-app.default(O): Error: EACCES: permission denied, open '/hab/pkgs/mattray/sample-node-app/1.0.1/20180205060828/app/bin/www'
sample-node-app.default(O):   at Object.fs.openSync (fs.js:646:18)
sample-node-app.default(O):   at Object.fs.readFileSync (fs.js:551:33)
sample-node-app.default(O):   at Object.Module._extensions..js (module.js:645:20)
sample-node-app.default(O):   at Module.load (module.js:554:32)
sample-node-app.default(O):   at tryModuleLoad (module.js:497:12)
sample-node-app.default(O):   at Function.Module._load (module.js:489:3)
sample-node-app.default(O):   at Function.Module.runMain (module.js:676:10)
sample-node-app.default(O):   at startup (bootstrap_node.js:187:16)
sample-node-app.default(O):   at bootstrap_node.js:608:3
hab-launch(SV): Child for service 'sample-node-app.default' with PID 42 exited with code exit code: 1
```

**Comment by chefsalim** [comment]
Issue moved to [habitat-sh/builder #144](https://github.com/habitat-sh/builder/issues/144) via [**ZenHub**](https://www.zenhub.com/)
