### ISSUE TITLE
`hab config show $IDENT` fails with panic on Result::unwrap()

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat#5109]
While investigating some of the functionality around `protocol::ctl::SvcGetDefaultCfg` for obtaining service config, I think I've discovered a bug with what's in master (0.56.0)

Here is the result of my trying to run the command on recently compiled source on my Mac when in `make shell`:

```bash
root@4a0d5161a919:/src# set | grep HAB
HAB_BLDR_URL=
HAB_BUTTERFLY_BINARY=/src/target/debug/butterfly
HAB_LAUNCH_BINARY=/src/target/debug/hab-launch
HAB_ORIGIN=jeremymv2
HAB_SUP_BINARY=/src/target/debug/hab-sup
root@4a0d5161a919:/src# ./target/debug/hab --version
hab 0.56.0
root@4a0d5161a919:/src# ./target/debug/hab sup run &
[1] 4440
root@4a0d5161a919:/src# hab-sup(MR): Supervisor Member-ID 557ce05751b04c3ebd04b292995ff018
hab-sup(MR): Starting core/redis
redis.default(UCW): Watching user.toml
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting ctl-gateway on 127.0.0.1:9632
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
redis.default(HK): Hooks compiled
redis.default(SR): Initializing
redis.default(SV): Starting service as user=hab, group=hab
redis.default(O):                 _._
redis.default(O):            _.-``__ ''-._
redis.default(O):       _.-``    `.  `_.  ''-._           Redis 3.2.4 (00000000/0) 64 bit
redis.default(O):   .-`` .-```.  ```\/    _.,_ ''-._
redis.default(O):  (    '      ,       .-`  | `,    )     Running in standalone mode
redis.default(O):  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis.default(O):  |    `-._   `._    /     _.-'    |     PID: 4493
redis.default(O):   `-._    `-._  `-./  _.-'    _.-'
redis.default(O):  |`-._`-._    `-.__.-'    _.-'_.-'|
redis.default(O):  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis.default(O):   `-._    `-._`-.__.-'_.-'    _.-'
redis.default(O):  |`-._`-._    `-.__.-'    _.-'_.-'|
redis.default(O):  |    `-._`-._        _.-'_.-'    |
redis.default(O):   `-._    `-._`-.__.-'_.-'    _.-'
redis.default(O):       `-._    `-.__.-'    _.-'
redis.default(O):           `-._        _.-'
redis.default(O):               `-.__.-'
redis.default(O):
redis.default(O): 4493:M 22 May 14:39:07.124 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis.default(O): 4493:M 22 May 14:39:07.124 # Server started, Redis version 3.2.4
redis.default(O): 4493:M 22 May 14:39:07.124 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis.default(O): 4493:M 22 May 14:39:07.124 * DB loaded from disk: 0.000 seconds
redis.default(O): 4493:M 22 May 14:39:07.124 * The server is now ready to accept connections on port 6379

root@4a0d5161a919:/src# ./target/debug/hab svc status core/redis                               │
package                          type        state  uptime (s)  pid   group                    │
core/redis/3.2.4/20170514150022  standalone  up     18          4558  redis.default            │
root@4a0d5161a919:/src# ./target/debug/hab config show core/redis
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: habitat_sup::manager::Manager::service_cfg
             at components/sup/src/manager/mod.rs:776
  12: <habitat_sup::ctl_gateway::server::SrvHandler as futures::future::Future>::poll::{{closure}}
             at components/sup/src/ctl_gateway/server.rs:289
  13: habitat_sup::ctl_gateway::server::CtlCommand::run
             at components/sup/src/ctl_gateway/server.rs:144
  14: <habitat_sup::manager::CtlHandler as futures::future::Future>::poll
             at components/sup/src/manager/mod.rs:1880
  15: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/mod.rs:113
  16: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  17: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  18: futures::task_impl::std::set
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/std/mod.rs:78
  19: <futures::task_impl::Spawn<T>>::enter
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  20: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  21: tokio_core::reactor::Core::dispatch_task::{{closure}}
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:359
  22: <scoped_tls::ScopedKey<T>>::set
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  23: tokio_core::reactor::Core::dispatch_task
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:358
  24: tokio_core::reactor::Core::dispatch
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:319
  25: tokio_core::reactor::Core::poll
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:307
  26: tokio_core::reactor::Core::turn
             at /cargo-cache/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:254
  27: habitat_sup::manager::Manager::run
             at components/sup/src/manager/mod.rs:762
  28: hab_sup::sub_run
             at components/sup/src/main.rs:251
  29: hab_sup::start
             at components/sup/src/main.rs:123
  30: hab_sup::main
             at components/sup/src/main.rs:72
  31: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  32: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  33: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  34: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  35: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  36: main
  37: __libc_start_main
  38: _start
✗✗✗
✗✗✗ Connection closed
✗✗✗
root@4a0d5161a919:/src# redis.default(SV): Stopping...
redis.default(O): 4493:signal-handler (1526999958) Received SIGTERM scheduling shutdown...
redis.default(O): 4493:M 22 May 14:39:18.074 # User requested shutdown...
redis.default(O): 4493:M 22 May 14:39:18.074 * Saving the final RDB snapshot before exiting.
redis.default(O): 4493:M 22 May 14:39:18.078 * DB saved on disk
redis.default(O): 4493:M 22 May 14:39:18.078 * Removing the pid file.
redis.default(O): 4493:M 22 May 14:39:18.078 # Redis is now ready to exit, bye bye...
redis.default(SV): Shutdown OK: Graceful Termination

[1]+  Done                    ./target/debug/hab sup run
root@4a0d5161a919:/src#
```

The problem seems to begin [here](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L776) perhaps.

**Comment by christophermaier** [comment]
Confirmed; I'll see if we can get this fixed today. Thanks for reporting @jeremymv2 !
