### ISSUE TITLE
`hab bldr job status` requires one of GROUP_ID or ORIGIN args, but must also allow both

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#5163]
Using the current `0.56.0` release I see this when running a `hab bldr job status` without additional arguments (note: found running on **macOS 10.12.16** and **Linux**):

macOS:

```sh
> hab  -V
hab 0.56.0/20180530234342

> hab bldr job status
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Linux:

```sh
> hab -V
hab 0.56.0/20180530234036

> hab bldr job status
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by baumanj** [comment]
I think this `(@attributes +required)` got lost in the shuffling around of a lot of our CLI handling. I checked to see if there were other places where it's missing and didn't see any others.

**Comment by baumanj** [comment]
It turns out [the breakage happened here](https://github.com/habitat-sh/habitat/commit/24da5999344abcccf6e1ae16cef35e04665f7e58#diff-ee10e75b553edc813cf07f6a5036374c), but it was an intentional change to allow both origin and group options. I'm reopening the issue and making the title more helpful.

**Comment by baumanj** [comment]
I misunderstood the situation. Per @chefsalim, we _don't_ need to support both `GROUP_ID` and `ORIGIN` args, so I think this works correctly:

```
➤ target/debug/hab bldr job status -o core
☁ Determining status of job groups in core origin

CREATED AT                        GROUP ID             STATUS    IDENT
2018-06-14T16:05:50.984834+00:00  1004335823479046144  Complete  core/mksh
2018-06-13T23:01:52.323123+00:00  1003820438627385344  Complete  core/hab
2018-06-13T22:59:15.940390+00:00  1003819126791692288  Complete  core/hab
2018-06-13T20:50:58.961322+00:00  1003754559852052480  Complete  core/hab
2018-06-13T20:50:37.952182+00:00  1003754383607390208  Complete  core/hab
2018-06-13T18:59:38.357047+00:00  1003698518867050496  Complete  core/hab
2018-06-13T18:58:55.294552+00:00  1003698157636804608  Complete  core/hab
2018-06-13T18:39:24.569246+00:00  1003688336883695616  Complete  core/hab
2018-06-13T18:39:24.395875+00:00  1003688335449235456  Complete  core/hab-pkg-export-kubernetes
2018-06-13T18:39:24.363507+00:00  1003688335180791808  Complete  core/hab-pkg-export-docker
```

```
➤ target/debug/hab bldr job status 1004346280097071104
☁ Determining status of job group 1004346280097071104

CREATED AT                        GROUP ID             STATUS       IDENT
2018-06-14T16:26:37.512868+00:00  1004346280097071104  Dispatching  baumanj/sample-node-app

```

```
➤ target/debug/hab bldr job status 1004346280097071104 -o core
error: The argument '--origin <ORIGIN>' cannot be used with one or more of the other specified arguments

USAGE:
    hab bldr job status <GROUP_ID|--origin <ORIGIN>>

For more information try --help
```
