### ISSUE TITLE
hab-sup panic in very large rings 

### ISSUE THREAD

**Issue by irvingpop** [habitat-sh/habitat#5867]
As discussed internally, we are "torture testing" the habitat supervisor in very large rings (ranging from 500 to 2000 nodes, via Kubernetes).   Using 0.68 as well as a master build from 2018/11/19, we are reliably seeing a panic happening all over the ring.

- [X] The OS (including version) where you are running any of the Habitat commands.
Containers inside of Kubernetes (GKE)

- [X] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
[2018-11-19T21:16:14Z ERROR habitat_butterfly::server::inbound] PingReq request PingReq { membership: [Membership { member: Member { id: "0fb7c8bac31e48a9ae9354fd4203acec", incarnation: Incarnation(0), address: "10.16.20.18", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, health: Alive }, Membership { member: Member { id: "cc62bef8cce94069ac38da1ebdf481e5", incarnation: Incarnation(0), address: "10.16.17.17", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, health: Alive }, Membership { member: Member { id: "9d0864df48964a399bd5c59472b70a06", incarnation: Incarnation(0), address: "10.16.18.11", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, health: Alive }, Membership { member: Member { id: "97c54cc6f27644069cd3707b6f682d2b", incarnation: Incarnation(0), address: "10.16.28.22", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, health: Alive }, Membership { member: Member { id: "f657befa799246d6b151d80f0ef3552c", incarnation: Incarnation(0), address: "10.16.28.13", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, health: Alive }, Membership { member: Member { id: "29c9bcbd658d42e28e7b3961d05d8280", incarnation: Incarnation(0), address: "10.16.30.16", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, health: Alive }], from: Member { id: "583da4d0c8f44134bbb26b196cc8dac6", incarnation: Incarnation(1), address: "10.16.17.15", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false }, target: Member { id: "0fb7c8bac31e48a9ae9354fd4203acec", incarnation: Incarnation(0), address: "10.16.20.18", swim_port: 9638, gossip_port: 9638, persistent: false, departed: false } } for invalid target
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: <core::option::Option<T>>::unwrap
             at libcore/macros.rs:20
  10: <habitat_butterfly::member::MemberListProxy<'a> as serde::ser::Serialize>::serialize
             at ./src/habitat/components/butterfly/src/member.rs:896
  11: <serde_json::ser::Compound<'a, W, F> as serde::ser::SerializeMap>::serialize_value
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.33/src/ser.rs:731
  12: <serde_json::ser::Compound<'a, W, F> as serde::ser::SerializeStruct>::serialize_field
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.33/src/ser.rs:779
  13: <habitat_butterfly::server::ServerProxy<'a> as serde::ser::Serialize>::serialize
             at ./src/habitat/components/butterfly/src/server/mod.rs:1244
  14: serde_json::ser::to_writer
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.33/src/ser.rs:2145
  15: serde_json::ser::to_vec
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.33/src/ser.rs:2179
  16: serde_json::ser::to_string
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.33/src/ser.rs:2210
  17: habitat_sup::manager::Manager::persist_butterfly_state
             at components/sup/src/manager/mod.rs:1479
  18: habitat_sup::manager::Manager::persist_state
             at components/sup/src/manager/mod.rs:1462
  19: habitat_sup::manager::Manager::run
             at components/sup/src/manager/mod.rs:806
  20: hab_sup::sub_run
             at components/sup/src/main.rs:179
  21: hab_sup::start
             at components/sup/src/main.rs:129
  22: hab_sup::main
             at components/sup/src/main.rs:73
  23: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  24: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  25: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  26: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  27: std::rt::lang_start
             at libstd/rt.rs:74
  28: main
  29: __libc_start_main
  30: _start
             at ../sysdeps/x86_64/start.S:108
```

**Comment by irvingpop** [comment]
@christophermaier stated that is coming from a member that doesn't have a health value

Also, here's a link to the kubernetes manifests we are using to repro:  https://github.com/irvingpop/irvingpop-hab-plans/tree/master/hab_load/kubernetes
