### ISSUE TITLE
hab-sup panic on studio exit

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#6374]
Apologies I don't have more info here, I can't reproduce this, but I did see it this morning and figured I would report it.

Using `hab` 0.78.0 I saw the following error when exiting a habitat studio that was running a large number of services:

```
[52][default:/src:0]# exit
logout
thread 'main' panicked at 'assertion failed: !dirp.is_null()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc_self-0.1.0/src/lib.rs:189:4                          
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2019-04-04T08:32:15Z ERROR habitat_sup::manager] Error polling CtlAcceptor shutdown trigger: Canceled                                                                         
[2019-04-04T08:32:28Z ERROR hab_launch] Launcher exiting with code 0
```

This was inside a docker-based studio.

**Comment by dmccown** [comment]
I hit the wrong button accident. I didn't mean to close the issue.

**Comment by stevendanna** [comment]
Potentially related, seen on 0.90.6 in chroot-based studio:

```
thread 'main' panicked at 'assertion failed: !dirp.is_null()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/palaver-0.2.1/src/file.rs:559:4
--
  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
