### ISSUE TITLE
Habitat Event Stream Beta does not reconnect if Automate is temporarily unavailable

### ISSUE THREAD

**Issue by ericcalabretta** [habitat-sh/habitat#6737]
The Habitat Event Stream Beta does not reconnect if Automate is temporarily unavailable. I simulated a brief network outage by blocking port 4222 in my Security Group & I also simulated a brief outage by performing `sudo chef-automate restart-services` In both conditions the supervisor was unable to re-establish the connection with Automate giving this error:

```
Jul 16 21:32:50 national-parks-2 hab[5179]: [2019-07-16T21:32:50Z ERROR habitat_sup::event] Failed to queue event: SendError("...")
```

The supervisor would re-establish the connection to Automate after a restart `sudo systemctl restart hab-sup` 

Version information:
CentOS Linux release 7.6.1810 (Core)
hab 0.82.0/20190605214032
Chef Automate Build: 20190716174013

Habitat would report 0.82.0 with `hab --version` but I have the 0.83.0-dev version installed per the beta.

`sudo hab pkg install core/hab-sup/0.83.0-dev -c unstable`

More detailed logs for both failures:

## 1. network unavailable:

removed inbound rule for 4222 from Automate security group to simulate temporary network failure 
tcp 4222 0.0.0.0/0

next check in error:
Jul 16 21:17:21 national-parks-2 hab[5179]: [2019-07-16T21:17:21Z ERROR ratsio::nats_client::client] Pings are not responded to, we may be down.
Jul 16 21:19:28 national-parks-2 hab[5179]: [2019-07-16T21:19:28Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 21:21:36 national-parks-2 hab[5179]: [2019-07-16T21:21:36Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 21:23:44 national-parks-2 hab[5179]: [2019-07-16T21:23:44Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 21:25:52 national-parks-2 hab[5179]: [2019-07-16T21:25:52Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 21:28:01 national-parks-2 hab[5179]: [2019-07-16T21:28:01Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError

Applications are still up and working correctly 

waited 10 minutes

after I re-added inbound rule I get these errors nearly instantly:

```
Jul 16 21:30:09 national-parks-2 hab[5179]: [2019-07-16T21:30:09Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 21:30:10 national-parks-2 hab[5179]: [2019-07-16T21:30:10Z ERROR ratsio::nats_client::client] NATS Server - Error - Authorization Violation
Jul 16 21:30:17 national-parks-2 hab[5179]: [2019-07-16T21:30:17Z ERROR habitat_sup::event::stream_impl] Error publishing event: InnerBrokenChain: the sender/receiver pair has been disconnected
Jul 16 21:30:20 national-parks-2 hab[5179]: [2019-07-16T21:30:20Z ERROR habitat_sup::event::stream_impl] Error publishing event: InnerBrokenChain: the sender/receiver pair has been disconnected
Jul 16 21:30:31 national-parks-2 hab[5179]: [2019-07-16T21:30:31Z ERROR ratsio::nats_client::client] Pings are not responded to, we may be down.
Jul 16 21:30:31 national-parks-2 hab[5179]: thread 'events' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
Jul 16 21:30:31 national-parks-2 hab[5179]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jul 16 21:30:38 national-parks-2 hab[5179]: [2019-07-16T21:30:38Z ERROR habitat_sup::event] Failed to queue event: SendError("...")
Jul 16 21:30:47 national-parks-2 hab[5179]: [2019-07-16T21:30:47Z ERROR habitat_sup::event] Failed to queue event: SendError("...")
```
This error continues at a regular interval:
```
Jul 16 21:32:50 national-parks-2 hab[5179]: [2019-07-16T21:32:50Z ERROR habitat_sup::event] Failed to queue event: SendError("...")
```
waited 10 minutes and no recovery
 
`sudo systemctl restart hab-sup`

access to Automate is restored

## 2. Simulated Automate upgrade with `sudo chef-automate restart-services`

```
Jul 16 22:01:42 national-parks-2 hab[32734]: [2019-07-16T22:01:42Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:43 national-parks-2 hab[32734]: [2019-07-16T22:01:43Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:44 national-parks-2 hab[32734]: [2019-07-16T22:01:44Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:45 national-parks-2 hab[32734]: [2019-07-16T22:01:45Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:46 national-parks-2 hab[32734]: [2019-07-16T22:01:46Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:47 national-parks-2 hab[32734]: [2019-07-16T22:01:47Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:48 national-parks-2 hab[32734]: [2019-07-16T22:01:48Z ERROR habitat_sup::event::stream_impl] Error publishing event: InnerBrokenChain: the sender/receiver pair has been disconnected
Jul 16 22:01:48 national-parks-2 hab[32734]: [2019-07-16T22:01:48Z ERROR habitat_sup::event::stream_impl] Error publishing event: InnerBrokenChain: the sender/receiver pair has been disconnected
Jul 16 22:01:48 national-parks-2 hab[32734]: [2019-07-16T22:01:48Z ERROR habitat_sup::event::stream_impl] Error publishing event: InnerBrokenChain: the sender/receiver pair has been disconnected
Jul 16 22:01:48 national-parks-2 hab[32734]: [2019-07-16T22:01:48Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:49 national-parks-2 hab[32734]: [2019-07-16T22:01:49Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:50 national-parks-2 hab[32734]: [2019-07-16T22:01:50Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:51 national-parks-2 hab[32734]: [2019-07-16T22:01:51Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:52 national-parks-2 hab[32734]: [2019-07-16T22:01:52Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:53 national-parks-2 hab[32734]: [2019-07-16T22:01:53Z ERROR ratsio::net::connection] Error reconnecting :: NoRouteToHostError
Jul 16 22:01:54 national-parks-2 hab[32734]: [2019-07-16T22:01:54Z ERROR ratsio::nats_client::client] NATS Server - Error - Authorization Violation
Jul 16 22:01:54 national-parks-2 hab[32734]: thread 'events' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
Jul 16 22:01:54 national-parks-2 hab[32734]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jul 16 22:02:18 national-parks-2 hab[32734]: [2019-07-16T22:02:18Z ERROR habitat_sup::event] Failed to queue event: SendError("...")
```

Errors continue till I restart the supervisors 

`sudo systemctl restart hab-sup`

access to Automate is restored

**Comment by OkJaybird** [comment]
I don't think this needs to do anything fancy out of the gate in terms of batching data, etc. Our preference would be once the supervisor is able to reconnect to Automate, it just continues business as usual and picks regular reporting back up at that point.

**Comment by christophermaier** [comment]
I think for now what @OkJaybird suggests is probably the way to go... if we're currently not able to communicate with Automate, we drop the event on the floor and don't worry about keeping a backlog to send later when we reestablish communications. Once we can communicate with Automate again, we just send whatever the currently-occurring events are.

Initially, I was concerned about what might happen if, say, a new service starts up during the time when Automate is unreachable... if we dropped that event on the floor, there wouldn't be any way to resend it when contact was reestablished, and Automate might get badly out of sync. But as @danielsdeleo pointed out in an offline discussion, the health check events that are currently sent out contain pretty much all the information about a service that you would want, and the dashboard data is largely derived from just that data. Since health checks generally run every 30 seconds, Automate would pretty quickly catch up to the current state of the world once a Supervisor reestablished contact with it.

Since that's about the extent of the events we send out right now, I don't think we lose much at all from a "drop it on the floor" policy, and we gain a lot in simplicity. This is a decision we might have to revisit in the future, if we started sending out other events that are less able to "heal" the state in Automate... alternatively, we could take this as a design constraint to inform the design and consumption of those future events in order to allow us to _keep_ that simplicity.

**Comment by davidMcneil** [comment]
I am moving this to "in development" because #6770 will likely yield a better long term solution.
