### ISSUE TITLE
Errors with migrating to executors on single file test

### ISSUE THREAD

**Issue by scotthain** [habitat-sh/habitat#7000]
While migrate to executors from default (old style) queues, we've run into an issue with one of the file tests:
https://github.com/habitat-sh/habitat/blob/9f8433b962673835fdab5652f208469a92c2d157/components/common/src/templating/config.rs#L1055-L1073

Error can be found here:
https://buildkite.com/chef/habitat-sh-habitat-master-verify/builds/3666#ae448100-387f-4f4c-a62f-c8e3973a1f02

Backtrace is as follows:
```



---- templating::config::test::write_template_file_no_perms stdout ----
  | thread 'templating::config::test::write_template_file_no_perms' panicked at 'assertion failed: write_templated_file(&file, &contents, &curr_username(),
  | &curr_groupname()).is_err()', components/common/src/templating/config.rs:1070:9
  | stack backtrace:
  | 0: backtrace::backtrace::libunwind::trace
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
  | 1: backtrace::backtrace::trace_unsynchronized
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
  | 2: std::sys_common::backtrace::_print
  | at src/libstd/sys_common/backtrace.rs:47
  | 3: std::sys_common::backtrace::print
  | at src/libstd/sys_common/backtrace.rs:36
  | 4: std::panicking::default_hook::{{closure}}
  | at src/libstd/panicking.rs:200
  | 5: std::panicking::default_hook
  | at src/libstd/panicking.rs:211
  | 6: std::panicking::rust_panic_with_hook
  | at src/libstd/panicking.rs:477
  | 7: std::panicking::begin_panic
  | at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
  | 8: habitat_common::templating::config::test::write_template_file_no_perms
  | at components/common/src/templating/config.rs:1070
  | 9: habitat_common::templating::config::test::write_template_file_no_perms::{{closure}}
  | at components/common/src/templating/config.rs:1057
  | 10: core::ops::function::FnOnce::call_once
  | at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  | 11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  | at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  | 12: __rust_maybe_catch_panic
  | at src/libpanic_unwind/lib.rs:82
  | 13: std::panicking::try
  | at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  | 14: std::panic::catch_unwind
  | at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  | 15: test::run_test::run_test_inner::{{closure}}
  | at src/libtest/lib.rs:1466
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  |  
  |  
  | failures:
  | templating::config::test::write_template_file_no_perms
 

```

**Comment by mwrock** [comment]
closing due to lack of activity
