### ISSUE TITLE
some pip-installed Python modules give a CERTIFICATE_VERIFY_FAILED error during build

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#945]
For example:

```
    Download error on https://pypi.python.org/simple/numpy/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.
c:590) -- Some packages may not be found!
    Couldn't find index page for 'numpy' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
 -- Some packages may not be found!
    No local packages or download links found for numpy>=1.6
    Traceback (most recent call last):
      File "<string>", line 1, in <module>

      File "/tmp/pip-build-j0adA9/numexpr/setup.py", line 219, in <module>
        setup_package()
      File "/tmp/pip-build-j0adA9/numexpr/setup.py", line 215, in setup_package
        setup(**metadata)
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init_
_
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_b
uild_eggs
        replace_conflicting=True,
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in
resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in
 best_match
        return self.obtain(req, installer)
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in
 obtain
        return installer(requirement)
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_b
uild_egg
        return cmd.easy_install(req)
      File "/hab/pkgs/core/python2/2.7.11/20160620182552/lib/python2.7/site-packages/setuptools/command/easy_install.py", line
 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy>=1.6')
```

Relevant `plan.sh` lines (this is a build plan embedded at `private_repo/habitat/plan.sh`):

```
pkg_deps=(core/glibc core/gcc core/python2)
pkg_build_deps=(core/gcc core/make core/python2 core/git)
pkg_bin_dirs=(bin)
pkg_lib_dirs=(lib)
pkg_include_dirs=(include)

do_download(){
  return 0
}

do_verify(){
  return 0
}

do_unpack(){
  return 0
}

do_build(){
  pushd /src > /dev/null
  pwd
  pip install --upgrade pip
  pip install --install-option="--prefix=${pkg_prefix}" $(grep numpy requirements.txt)
  pip install --install-option="--prefix=${pkg_prefix}" $(grep numexpr requirements.txt)
  pip install --install-option="--prefix=${pkg_prefix}" $(grep Cython requirements.txt)
  pip install --install-option="--prefix=${pkg_prefix}" -r requirements.txt
  popd > /dev/null
}

do_install(){
  pushd $PLAN_CONTEXT > /dev/null
  pip install -e .
  popd > /dev/null
}
```

**Comment by bixu** [comment]
Example repo to reproduces this is here: https://github.com/bixu/python-habitat

**Comment by adamhjk** [comment]
Thanks for the sample repo - lets work with the maintainers to figure this out, since we obviously want the experience with python to be easy.

**Comment by bixu** [comment]
Perhaps this is an issue with `core/openssl`? Ran this from inside my interactive build:
```
openssl s_client -connect pypi.python.org:443 > openssl_check.txt
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server CA
verify error:num=20:unable to get local issuer certificate
```

**Comment by smith** [comment]
According to an `strace openssl s_client -connect pypi.python.org:443` on my machine, OpenSSL is looking for certs here:

```
open("/hab/pkgs/core/openssl/1.0.2h/20160612081127/ssl/cert.pem", O_RDONLY) = -1 ENOENT (No such file or directory)
```

But it should probably be looking in /hab/pkgs/core/cacerts/2016.04.20/20160612081125/ssl/cert.pem.

I think this may be being set incorrectly in the openssl plan.

**Comment by smith** [comment]
Built and uploaded to depot https://app.habitat.sh/#/pkgs/core/logstash/2.3.3/20160628175751

**Comment by bixu** [comment]
I'm not following why the logstash build is showing up here..?

**Comment by smith** [comment]
Sorry wrong issue.

**Comment by smith** [comment]
#1007 could be the cause of this.

**Comment by bixu** [comment]
I don't follow - I think in my example repo we are not doing a traditional `make install`?

**Comment by smith** [comment]
@bixu the reason I'm saying it's related is that there appears to be a problem with OpenSSL locating certs, and function patched some files in the OpenSSL compilation to fix cert locations.

**Comment by smith** [comment]
If you run `make test` against the python plan, you end up getting:

```
======================================================================
ERROR: test_connect (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1369, in test_connect
    s.connect(("svn.python.org", 443))
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1014, in connect
    self._real_connect(addr, False)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1005, in _real_connect
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_connect_cadata (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1514, in test_connect_cadata
    s.connect(("svn.python.org", 443))
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1014, in connect
    self._real_connect(addr, False)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1005, in _real_connect
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_connect_capath (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1487, in test_connect_capath
    s.connect(("svn.python.org", 443))
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1014, in connect
    self._real_connect(addr, False)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1005, in _real_connect
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_connect_ex (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1381, in test_connect_ex
    self.assertEqual(0, s.connect_ex(("svn.python.org", 443)))
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1019, in connect_ex
    return self._real_connect(addr, True)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1005, in _real_connect
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_connect_with_context (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1469, in test_connect_with_context
    s.connect(("svn.python.org", 443))
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1014, in connect
    self._real_connect(addr, False)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1005, in _real_connect
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_get_ca_certs_capath (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1649, in test_get_ca_certs_capath
    s.connect(("svn.python.org", 443))
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1014, in connect
    self._real_connect(addr, False)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1005, in _real_connect
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_get_server_certificate (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1593, in test_get_server_certificate
    _test_get_server_certificate('svn.python.org', 443, SVN_PYTHON_ORG_ROOT_CERT)
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1587, in _test_get_server_certificate
    ca_certs=cert)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 1138, in get_server_certificate
    with context.wrap_socket(sock) as sslsock:
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_non_blocking_connect_ex (test.test_ssl.NetworkedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1404, in test_non_blocking_connect_ex
    s.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

======================================================================
ERROR: test_handshake (test.test_ssl.NetworkedBIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1731, in test_handshake
    self.ssl_io_loop(sock, incoming, outgoing, sslobj.do_handshake)
  File "/hab/cache/src/Python-3.5.1/Lib/test/test_ssl.py", line 1684, in ssl_io_loop
    ret = func(*args)
  File "/hab/cache/src/Python-3.5.1/Lib/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

**Comment by bixu** [comment]
Looks like we need a new core/python build with perhaps adjusted compile flags with regard to OpenSSL/certs?

**Comment by bixu** [comment]
I'd love to help work on this, but I think I need some help, or I can help test, as I have a fairly big `requirements.txt` use-case.

**Comment by bixu** [comment]
This is specifically reproducible running `pip install numexpr==2.4`, even after exporting `PIP_CERT=$(pkg_path_for core/cacerts)/ssl/certs/cacert.pem`

**Comment by bixu** [comment]
Pinning numexpr to version 2.6.1 seems to be an effective workaround, so I'm no longer sure if this is a Habitat bug or a bug with the numexpr module. I'm inclined to close this issue until we can prove it's not numexpr.

**Comment by bixu** [comment]
I keep finding that updating the versions of pip modules allows me to work around the SSL errors. This makes me think that pip is not able to 'see' Habitat-provided SSL certs, and is therefore defaulting to certs that ship with the modules (this seems to be more common in recent versions of modules). So maybe the problem lies in how Habitat is making SSL cert locations known? I don't understand the internals of the core/openssl package as of yet...

**Comment by bixu** [comment]
From the Habichat, this seems relevant (have not yet tried):  https://access.redhat.com/articles/2039753

**Comment by bixu** [comment]
Working `plan.sh` snippet for pip-installing from a private projects `requirements.txt` file:
```
do_install(){
  export SSL_CERT_FILE=$(hab pkg path core/cacerts)/ssl/cert.pem
  cd $PLAN_CONTEXT
  pip install $(grep numpy ../requirements.txt)
  attach
  pip install -r ../requirements.txt
  pip install -e ../
}
```

**Comment by fnichol** [comment]
We're going to move this issue into habitat-sh/core-plans#338 to make sure this gets addressed, thanks all!
